[package]
name = "oscar-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.96"
walkdir = "2"
zstd = "0.12.3"
oscar-io = "0.2.3"
warc = "0.3.1"
